version: "3.9"
services:
  mysql:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql

volumes:
 mysql_data_container:
